"""Shared configuration for all pipelines."""

import os

from dotenv import load_dotenv

load_dotenv(override=True)

GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID", "practical-gecko-373320")
BIGQUERY_LOCATION = os.getenv("BIGQUERY_LOCATION", "us-west1")

# Amazon Ads
AMAZON_CLIENT_ID = os.getenv("AMAZON_CLIENT_ID", "")
AMAZON_CLIENT_SECRET = os.getenv("AMAZON_CLIENT_SECRET", "")
AMAZON_REFRESH_TOKEN = os.getenv("AMAZON_REFRESH_TOKEN", "")
AMAZON_PROFILE_IDS = [
    p.strip() for p in os.getenv("AMAZON_PROFILE_IDS", "").split(",") if p.strip()
]

# Amazon SP-API (Seller Central — separate app from Ads)
SP_API_CLIENT_ID = os.getenv("SP_API_CLIENT_ID", "")
SP_API_CLIENT_SECRET = os.getenv("SP_API_CLIENT_SECRET", "")
SP_API_REFRESH_TOKEN = os.getenv("SP_API_REFRESH_TOKEN", "")
SP_API_MARKETPLACE_ID = os.getenv("SP_API_MARKETPLACE_ID", "ATVPDKIKX0DER")

# Shopify
SHOPIFY_SHOP_DOMAIN = os.getenv("SHOPIFY_SHOP_DOMAIN", "")
SHOPIFY_CLIENT_ID = os.getenv("SHOPIFY_CLIENT_ID", "")
SHOPIFY_CLIENT_SECRET = os.getenv("SHOPIFY_CLIENT_SECRET", "")
SHOPIFY_ACCESS_TOKEN = os.getenv("SHOPIFY_ACCESS_TOKEN", "")
SHOPIFY_API_VERSION = os.getenv("SHOPIFY_API_VERSION", "2025-01")

# Meta Ads
META_ADS_ACCOUNT_ID = os.getenv("META_ADS_ACCOUNT_ID", "")
META_APP_ID = os.getenv("META_APP_ID", "")
META_APP_SECRET = os.getenv("META_APP_SECRET", "")
META_ACCESS_TOKEN = os.getenv("META_ACCESS_TOKEN", "")
META_API_VERSION = os.getenv("META_API_VERSION", "v21.0")

# Google Ads
GOOGLE_ADS_CUSTOMER_ID = os.getenv("GOOGLE_ADS_CUSTOMER_ID", "").replace("-", "")
GOOGLE_ADS_DEVELOPER_TOKEN = os.getenv("GOOGLE_ADS_DEVELOPER_TOKEN", "")
GOOGLE_ADS_CLIENT_ID = os.getenv("GOOGLE_ADS_CLIENT_ID", "")
GOOGLE_ADS_CLIENT_SECRET = os.getenv("GOOGLE_ADS_CLIENT_SECRET", "")
GOOGLE_ADS_REFRESH_TOKEN = os.getenv("GOOGLE_ADS_REFRESH_TOKEN", "")
GOOGLE_ADS_LOGIN_CUSTOMER_ID = os.getenv("GOOGLE_ADS_LOGIN_CUSTOMER_ID", "").replace("-", "")

# Google Search Console
GOOGLE_SEARCH_CONSOLE_CLIENT_ID = os.getenv("GOOGLE_SEARCH_CONSOLE_CLIENT_ID", "")
GOOGLE_SEARCH_CONSOLE_CLIENT_SECRET = os.getenv("GOOGLE_SEARCH_CONSOLE_CLIENT_SECRET", "")
GOOGLE_SEARCH_CONSOLE_REFRESH_TOKEN = os.getenv("GOOGLE_SEARCH_CONSOLE_REFRESH_TOKEN", "")
GOOGLE_SEARCH_CONSOLE_SITE_URL = os.getenv("GOOGLE_SEARCH_CONSOLE_SITE_URL", "")
GOOGLE_SEARCH_CONSOLE_SITE_URL_SHOP = os.getenv("GOOGLE_SEARCH_CONSOLE_SITE_URL_SHOP", "")

# QuickBooks
QUICKBOOKS_CLIENT_ID = os.getenv("QUICKBOOKS_CLIENT_ID", "")
QUICKBOOKS_CLIENT_SECRET = os.getenv("QUICKBOOKS_CLIENT_SECRET", "")
QUICKBOOKS_REFRESH_TOKEN = os.getenv("QUICKBOOKS_REFRESH_TOKEN", "")
QUICKBOOKS_REALM_ID = os.getenv("QUICKBOOKS_REALM_ID", "")

# PayPal
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID", "")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET", "")

# Google Merchant Center
MERCHANT_CENTER_ID = os.getenv("MERCHANT_CENTER_ID", "")
MERCHANT_CENTER_SA_KEY_JSON = os.getenv("MERCHANT_CENTER_SA_KEY_JSON", "")

# Klaviyo
KLAVIYO_API_KEY = os.getenv("KLAVIYO_API_KEY", "")

# Pipeline defaults
PIPELINE_ROLLING_DAYS = int(os.getenv("PIPELINE_ROLLING_DAYS", "7"))
PIPELINE_POLL_INTERVAL = int(os.getenv("PIPELINE_POLL_INTERVAL", "120"))
PIPELINE_POLL_TIMEOUT_MINUTES = int(os.getenv("PIPELINE_POLL_TIMEOUT_MINUTES", "45"))
